"""init

Revision ID: 18be7c1bc178
Revises: 
Create Date: 2025-10-27 16:32:02.075302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18be7c1bc178'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remark_docs',

    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(), nullable=True, comment='Примечание к замечаниям'),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),

    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('md5')
    )
    op.create_index(op.f('ix_remark_docs_created_at'), 'remark_docs', ['created_at'], unique=False)
    op.create_index(op.f('ix_remark_docs_id'), 'remark_docs', ['id'], unique=False)
    op.create_index(op.f('ix_remark_docs_project_id'), 'remark_docs', ['project_id'], unique=False)
    op.create_index(op.f('ix_remark_docs_section_id'), 'remark_docs', ['section_id'], unique=False)

    op.create_table('remarks',

    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False, comment='Порядковый номер замечания'),
    sa.Column('section_id', sa.Uuid(), nullable=False, comment='ID раздела документации'),
    sa.Column('expert_id', sa.Uuid(), nullable=False, comment='ID эксперта'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Дата замечания'),
    sa.Column('body', sa.String(), nullable=False, comment='Текст замечания'),
    sa.Column('link', sa.String(), nullable=False, comment='Ссылка на источник замечания в разделе'),
    sa.Column('basis', sa.String(), nullable=False, comment='Нормативное обоснование замечания'),
    sa.Column('remark_doc_id', sa.Uuid(), nullable=False),

    sa.ForeignKeyConstraint(['remark_doc_id'], ['remark_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remarks_created_at'), 'remarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_remarks_date'), 'remarks', ['date'], unique=False)
    op.create_index(op.f('ix_remarks_id'), 'remarks', ['id'], unique=False)
    op.create_index(op.f('ix_remarks_remark_doc_id'), 'remarks', ['remark_doc_id'], unique=False)
    op.create_index(op.f('ix_remarks_section_id'), 'remarks', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remarks_section_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_remark_doc_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_date'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_created_at'), table_name='remarks')
    op.drop_table('remarks')
    op.drop_index(op.f('ix_remark_docs_section_id'), table_name='remark_docs')
    op.drop_index(op.f('ix_remark_docs_project_id'), table_name='remark_docs')
    op.drop_index(op.f('ix_remark_docs_id'), table_name='remark_docs')
    op.drop_index(op.f('ix_remark_docs_created_at'), table_name='remark_docs')
    op.drop_table('remark_docs')
    # ### end Alembic commands ###
