"""add timezones to projects

Revision ID: bc7b4bc420aa
Revises: 1479e8344c5d
Create Date: 2025-11-26 12:56:58.906623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc7b4bc420aa'
down_revision: Union[str, Sequence[str], None] = '1479e8344c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'exp_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_comment='Срок экспертизы',
               existing_nullable=True)
    op.alter_column('projects', 'next_upload',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_comment='Крайний срок следующей загрузки в экспертизу',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'next_upload',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Крайний срок следующей загрузки в экспертизу',
               existing_nullable=True)
    op.alter_column('projects', 'exp_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Срок экспертизы',
               existing_nullable=True)
    # ### end Alembic commands ###
