"""unnecessary_fields

Revision ID: 1479e8344c5d
Revises: 31862dd732e4
Create Date: 2025-10-27 12:57:29.087962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1479e8344c5d'
down_revision: Union[str, Sequence[str], None] = '31862dd732e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'responsible_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Ответственный исполнитель')
    op.alter_column('sections', 'expert_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Эксперт')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'expert_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Эксперт')
    op.alter_column('sections', 'responsible_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Ответственный исполнитель')
    # ### end Alembic commands ###
