"""remove doc_path field

Revision ID: 759b6f0d7e30
Revises: 7c1b89529393
Create Date: 2025-10-21 18:05:15.353641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759b6f0d7e30'
down_revision: Union[str, Sequence[str], None] = '7c1b89529393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'doc_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
