"""add uploaded field and made md5 optional

Revision ID: e981a24cfe47
Revises: 759b6f0d7e30
Create Date: 2025-12-02 11:35:19.849815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e981a24cfe47'
down_revision: Union[str, Sequence[str], None] = '759b6f0d7e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('documents', sa.Column('uploaded', sa.Boolean(), nullable=True))
    op.execute("UPDATE documents SET uploaded = TRUE")
    op.alter_column('documents', 'uploaded', nullable=False)

    op.alter_column('documents', 'md5',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'md5',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('documents', 'uploaded')
    # ### end Alembic commands ###
