"""doc_path

Revision ID: 7c1b89529393
Revises: b0f8ff5c93f4
Create Date: 2025-09-24 18:40:24.507713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1b89529393'
down_revision: Union[str, Sequence[str], None] = 'b0f8ff5c93f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_path', sa.String(), nullable=True))
    op.alter_column('documents', 'version',
               existing_type=sa.INTEGER(),
               comment='Used on expertise',
               existing_nullable=False)
    op.alter_column('documents', 'variation',
               existing_type=sa.INTEGER(),
               comment='Continuous numbering for every document',
               existing_nullable=False)
    op.create_unique_constraint(None, 'documents', ['md5'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.alter_column('documents', 'variation',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Continuous numbering for every document',
               existing_nullable=False)
    op.alter_column('documents', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Used on expertise',
               existing_nullable=False)
    op.drop_column('documents', 'doc_path')
    # ### end Alembic commands ###
